apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: svcm-park-connect
  labels:
    release: prom
spec:
  selector:
    matchLabels:
      app: park-connect
  endpoints:
  - port: park-connect-port
    path: '/actuator/prometheus'
  namespaceSelector:
    matchNames: 
    - rob-workshop